version: '3'

volumes:
  pg_data_kit:
  static_kit:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_kit:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static_kit:/backend_static
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static_kit:/static
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_kit:/static
